import { useMemo } from "react";

 const products =  [
    { id: 1, name: "MTR Ready to Eat Chana Masala" },
    { id: 2, name: "MTR Ready To Eat Paneer Butter Masala" },
    { id: 3, name: "MTR Dal Makhani" },
    { id: 4, name: "MTR Breakfast Khatta Meetha Poha Mix" },
    { id: 5, name: "MTR Vegetable Upma" },
    { id: 6, name: "MTR 3 Min Poha" },
    { id: 7, name: "Cornitos Nacho Chips Sizzlin Jalapeno" },
    { id: 8, name: "Kurkure Yummy PuffCorn Yummy Cheese" },
    { id: 9, name: "Bingo! Mad Angles Achaari Masti" },
    { id: 10, name: "Kurkure Masala Munch" },
    { id: 11, name: "Korean Kab's Jackpot Ramyun Soup Noodles" },
    { id: 12, name: "Nissin Geki - Hot & Spicy Korean Chicken Flavour" },
    { id: 13, name: "Nissin Geki - Hot & Spicy Korean Cheese" },
    { id: 14, name: "Nissin Geki - Hot & Spicy Korean Veg Flavour" },
    { id: 15, name: "YiPPee! Korean Noodles Spicy Kimchi" },
    { id: 16, name: "YiPPee! Korean Noodles Fiery Hot" },
    { id: 17, name: "Too Yumm! K-Bomb Hot n Spicy" },
    { id: 18, name: "Top Ramen Noodles Curry" },
    { id: 19, name: "MAGGI Chicken Noodles" },
    { id: 20, name: "MAGGI Special Masala Instant Noodles" },
    { id: 21, name: "MAGGI 2-Minute Instant Masala Noodles" },
    { id: 22, name: "Sunfeast Yippee Tricolor Pasta Masala" },
    { id: 23, name: "Sunfeast Yippee Pasta Treat-Cheese" },
    { id: 24, name: "MAGGI Pazzta Instant Pasta - Mushroom Penne" },
    { id: 25, name: "MAGGI Pazzta Instant Pasta - Masala Penne" },
    { id: 26, name: "MAGGI Pazzta Instant Pasta - Cheese Macaroni" },
    { id: 27, name: "MAGGI Pazzta Instant Pasta - Cheesy Tomato Twist" },
    { id: 28, name: "Charliee Til Laddu" },
    { id: 29, name: "Bikaji Anjeer Dryfruit Burfee" },
    { id: 30, name: "Amul Frozen Rasmalai" },
    { id: 31, name: "Haldiram's Soan Papdi" },
    { id: 32, name: "Cham Cham by Haldiram's Nagpur" },
    { id: 33, name: "Kinder Joy Chocolate Snack" },
    { id: 34, name: "Kinder Schoko-Bons Crispy" },
    { id: 35, name: "Chupa Chups Sour Bites Mixed Fruit Flavour" },
    { id: 36, name: "Alpenliebe Juzt Jelly Strawberry Flavour" },
    { id: 37, name: "Alpenliebe Gold Cream Strawberry Candy" },
    { id: 38, name: "Nestle Munch Chocolate" },
    { id: 39, name: "Cadbury Gems" },
    { id: 40, name: "Cadbury 5 Star" },
    { id: 41, name: "Cadbury Dairy Milk Crispello" },
    { id: 42, name: "Nestle KitKat" },
    { id: 43, name: "Cadbury Nutties Chocolate Pack" },
    { id: 44, name: "Bounty Miniatures Coconut Filled Chocolate" },
    { id: 45, name: "Paper Boat Swing Pomegranate Juice" },
    { id: 46, name: "Paper Boat Chilli Guava Juice (2)" },
    { id: 47, name: "Paper Boat Chilli Guava Juice" },
    { id: 48, name: "Paper Boat Jamun Drink" },
    { id: 49, name: "Paper Boat Aam Panna Drink" },
    { id: 50, name: "Knorr Dark Soya Sauce" },
    { id: 51, name: "Ching's Secret Chilli Vinegar" },
    { id: 52, name: "Ching's Secret Red Chilli Sauce" },
    { id: 53, name: "Ching's Secret Green Chilli Sauce" },
    { id: 54, name: "Ching's Secret Dark Soy Sauce" },
    { id: 55, name: "Veeba Pasta & Pizza Sauce Herby Tomato" },
    { id: 56, name: "Amul Cheese Spread Yummy Plain" },
    { id: 57, name: "Nutella Hazelnut Spread with Cocoa" },
    { id: 58, name: "Peanut Butter with Honey" },
    { id: 59, name: "Kissan Mixed Fruit Jam" },
    { id: 60, name: "Saffola Masala Oats Veggie Twist" },
    { id: 61, name: "Saffola Masala Oats Classic Masala" },
    { id: 62, name: "Bingo Tedhe Medhe Chips" },
    { id: 63, name: "Biscoff Vanilla Cookies Biscuit" },
    { id: 64, name: "Britannia Bis Cafe Biscuit" },
    { id: 65, name: "Britannia Bourbon Biscuit" },
    { id: 66, name: "Britannia Gobbles Cake" },
    { id: 67, name: "Britannia Good Day (Pista Badam) Biscuit" },
    { id: 68, name: "Britannia Jim Jam Biscuit" },
    { id: 69, name: "Britannia Little Hearts Biscuit" },
    { id: 70, name: "Britannia Marie Biscuit" },
    { id: 71, name: "Britannia Milk Bikis Biscuit" },
    { id: 72, name: "Britannia Nice Biscuit" },
    { id: 73, name: "Britannia Nutri Choice (Almond Oats) Biscuit" },
    { id: 74, name: "Britannia Nutri Choice (Orange Almonds) Biscuit" },
    { id: 75, name: "Cadbury Chocobakes Biscuit" },
    { id: 76, name: "Cadbury Oreo Biscuit" },
    { id: 77, name: "Ching Dark Soy Sauce Sauce" },
    { id: 78, name: "Dr. Oetkar Mayonnaise Sauce" },
    { id: 79, name: "Ezaki Glico Pocky (Sticks) Biscuit" },
    { id: 80, name: "Haldiram Aloo Bhujia Shev" },
    { id: 81, name: "Haldiram Lite Chivda" },
    { id: 82, name: "Kissan Tomato Ketchup" },
    { id: 83, name: "Kurkure Masala Munch Chips" },
    { id: 84, name: "Kurkure Puffcorn Chips" },
    { id: 85, name: "Kurkure Solid Masti Masala Chips" },
    { id: 86, name: "Lays Chile Limon Chips" },
    { id: 87, name: "Lays Cream Onion Chips" },
    { id: 88, name: "Lays Hot 'n Sweet Chilli Chips" },
    { id: 89, name: "Lays Magic Masala Chips" },
    { id: 90, name: "Maggi Tomato Chilli Sauce" },
    { id: 91, name: "Parle Happy Happy Biscuit" },
    { id: 92, name: "Parle Hide & Seek Biscuit" },
    { id: 93, name: "Parle Hide & Seek (Coffee) Biscuit" },
    { id: 94, name: "Parle Krack Jack Biscuit" },
    { id: 95, name: "Parle Monaco Biscuit" },
    { id: 96, name: "Parle Parle G Biscuit" },
    { id: 97, name: "Sundrop Peanut Butter" },
    { id: 98, name: "Dark Fantasy Biscuit" },
    { id: 99, name: "Unibic Cashew Almond Cookies Biscuit" },
    { id: 100, name: "Unibic Chocochip Cookies Biscuit" },
    { id: 101, name: "Nestle Kit Kat Dark Chocolate Wafer" },
    { id: 102, name: "Cadbury Dairy Milk Crispello" },
    { id: 103, name: "Cadbury Dairy Milk Fruit & Nut" },
    { id: 104, name: "Cadbury Dairy Milk Silk Mousse" },
    { id: 105, name: "Cadbury Dairy Milk Silk Hazelnut" },
    { id: 106, name: "Cadbury Dairy Milk Silk Roast Almond" },
    { id: 107, name: "Cadbury Dairy Milk Silk Bubbly" },
    { id: 108, name: "Cadbury Dairy Milk Silk Oreo" },
    { id: 109, name: "Cadbury Dairy Milk Silk Fruit & Nut" },
    { id: 110, name: "Amul Vanilla Magic Ice Cream Tub" },
    { id: 111, name: "Amul Choco Chips Ice Cream Tub" },
    { id: 112, name: "Amul Vanilla Ice Cream" },
    { id: 113, name: "Amul Cookies 'n Cream Ice Cream" },
    { id: 114, name: "Amul Rajbhog Ice Cream" },
    { id: 115, name: "Amul Chocolate Magic Sundae Ice Cream" },
    { id: 116, name: "Amul Gold Butterscotch Ice Cream Tub" },
    { id: 117, name: "Kwality Walls Cornetto Double Chocolate Frozen Dessert Cone" },
    { id: 118, name: "Kwality Walls Magnum Chocolate Truffle Ice Cream Stick" },
    { id: 119, name: "Kwality Walls Shameless Vanilla Frozen Dessert Tub" },
    { id: 120, name: "Kwality Walls Kesar Pista Frozen Dessert Tub" },
    { id: 121, name: "Kwality Walls Oreo & Cream Frozen Dessert Tub" },
    { id: 122, name: "Kwality Walls Darkly Divine Chocolate Sensation Frozen Dessert Tub" },
    { id: 123, name: "Kwality Walls Hazelnut Chocolate Ice Cream" },
    { id: 124, name: "Kwality Walls Magnum Brownie Ice Cream Stick" },
    { id: 125, name: "Magnum Almond Ice Cream" },
    { id: 126, name: "Sprite" },
    { id: 127, name: "Limca" },
    { id: 128, name: "Mirinda" },
    { id: 129, name: "Zero Sugar Coke" },
    { id: 130, name: "Coke" },
    { id: 131, name: "Fanta" },
    { id: 132, name: "Fanta" },
    { id: 133, name: "Mountain Dew" },
    { id: 134, name: "Appy Fizz" },
    { id: 135, name: "Pepsi" },
    { id: 136, name: "Red Bull" },
    { id: 137, name: "Bisleri Limonata" },
    { id: 138, name: "Gatorade" },
    { id: 139, name: "Pepsico Gatorade (Orange)" },
    { id: 140, name: "Dabur Real (Masala Guava) Juice" },
    { id: 141, name: "Dabur Real (Apple) Juice" },
    { id: 142, name: "Pepsico Tropicana (Litchi) Juice" },
    { id: 143, name: "Pepsico Tropicana (Pineapple) Juice" },
    { id: 144, name: "Pepsico Tropicana (Pomegranate) Juice" },
                
    // Add more products up to 200
]; // Keeping products empty for this example

export default products;